# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from docentes.grpc_services import actividades_pb2 as actividades__pb2

GRPC_GENERATED_VERSION = '1.65.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in actividades_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class ActividadServiceStub(object):
    """Servicio para gestionar Actividades
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CrearActividad = channel.unary_unary(
                '/sga.docente.actividades.ActividadService/CrearActividad',
                request_serializer=actividades__pb2.CrearActividadRequest.SerializeToString,
                response_deserializer=actividades__pb2.ActividadResponse.FromString,
                _registered_method=True)
        self.EditarActividad = channel.unary_unary(
                '/sga.docente.actividades.ActividadService/EditarActividad',
                request_serializer=actividades__pb2.EditarActividadRequest.SerializeToString,
                response_deserializer=actividades__pb2.ActividadResponse.FromString,
                _registered_method=True)
        self.ObtenerActividad = channel.unary_unary(
                '/sga.docente.actividades.ActividadService/ObtenerActividad',
                request_serializer=actividades__pb2.ObtenerActividadRequest.SerializeToString,
                response_deserializer=actividades__pb2.ActividadResponse.FromString,
                _registered_method=True)
        self.ListarActividades = channel.unary_unary(
                '/sga.docente.actividades.ActividadService/ListarActividades',
                request_serializer=actividades__pb2.ListarActividadesRequest.SerializeToString,
                response_deserializer=actividades__pb2.ListarActividadesResponse.FromString,
                _registered_method=True)
        self.EliminarActividad = channel.unary_unary(
                '/sga.docente.actividades.ActividadService/EliminarActividad',
                request_serializer=actividades__pb2.EliminarActividadRequest.SerializeToString,
                response_deserializer=actividades__pb2.EliminarActividadResponse.FromString,
                _registered_method=True)


class ActividadServiceServicer(object):
    """Servicio para gestionar Actividades
    """

    def CrearActividad(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditarActividad(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerActividad(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarActividades(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EliminarActividad(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ActividadServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CrearActividad': grpc.unary_unary_rpc_method_handler(
                    servicer.CrearActividad,
                    request_deserializer=actividades__pb2.CrearActividadRequest.FromString,
                    response_serializer=actividades__pb2.ActividadResponse.SerializeToString,
            ),
            'EditarActividad': grpc.unary_unary_rpc_method_handler(
                    servicer.EditarActividad,
                    request_deserializer=actividades__pb2.EditarActividadRequest.FromString,
                    response_serializer=actividades__pb2.ActividadResponse.SerializeToString,
            ),
            'ObtenerActividad': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerActividad,
                    request_deserializer=actividades__pb2.ObtenerActividadRequest.FromString,
                    response_serializer=actividades__pb2.ActividadResponse.SerializeToString,
            ),
            'ListarActividades': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarActividades,
                    request_deserializer=actividades__pb2.ListarActividadesRequest.FromString,
                    response_serializer=actividades__pb2.ListarActividadesResponse.SerializeToString,
            ),
            'EliminarActividad': grpc.unary_unary_rpc_method_handler(
                    servicer.EliminarActividad,
                    request_deserializer=actividades__pb2.EliminarActividadRequest.FromString,
                    response_serializer=actividades__pb2.EliminarActividadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sga.docente.actividades.ActividadService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sga.docente.actividades.ActividadService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ActividadService(object):
    """Servicio para gestionar Actividades
    """

    @staticmethod
    def CrearActividad(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sga.docente.actividades.ActividadService/CrearActividad',
            actividades__pb2.CrearActividadRequest.SerializeToString,
            actividades__pb2.ActividadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EditarActividad(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sga.docente.actividades.ActividadService/EditarActividad',
            actividades__pb2.EditarActividadRequest.SerializeToString,
            actividades__pb2.ActividadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtenerActividad(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sga.docente.actividades.ActividadService/ObtenerActividad',
            actividades__pb2.ObtenerActividadRequest.SerializeToString,
            actividades__pb2.ActividadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarActividades(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sga.docente.actividades.ActividadService/ListarActividades',
            actividades__pb2.ListarActividadesRequest.SerializeToString,
            actividades__pb2.ListarActividadesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EliminarActividad(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sga.docente.actividades.ActividadService/EliminarActividad',
            actividades__pb2.EliminarActividadRequest.SerializeToString,
            actividades__pb2.EliminarActividadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
