# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from docentes.grpc_services import asistencia_pb2 as asistencia__pb2

GRPC_GENERATED_VERSION = '1.65.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in asistencia_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class AsistenciaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegistrarAsistenciaGrupal = channel.unary_unary(
                '/asistencia.AsistenciaService/RegistrarAsistenciaGrupal',
                request_serializer=asistencia__pb2.RegistrarAsistenciaGrupalRequest.SerializeToString,
                response_deserializer=asistencia__pb2.AsistenciaListResponse.FromString,
                _registered_method=True)
        self.ActualizarAsistencia = channel.unary_unary(
                '/asistencia.AsistenciaService/ActualizarAsistencia',
                request_serializer=asistencia__pb2.ActualizarAsistenciaRequest.SerializeToString,
                response_deserializer=asistencia__pb2.AsistenciaResponse.FromString,
                _registered_method=True)
        self.ConsultarAsistencia = channel.unary_unary(
                '/asistencia.AsistenciaService/ConsultarAsistencia',
                request_serializer=asistencia__pb2.ConsultarAsistenciaRequest.SerializeToString,
                response_deserializer=asistencia__pb2.AsistenciaListResponse.FromString,
                _registered_method=True)
        self.ConsultarResumenAsistencia = channel.unary_unary(
                '/asistencia.AsistenciaService/ConsultarResumenAsistencia',
                request_serializer=asistencia__pb2.ConsultarResumenRequest.SerializeToString,
                response_deserializer=asistencia__pb2.ResumenAsistenciaListResponse.FromString,
                _registered_method=True)


class AsistenciaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegistrarAsistenciaGrupal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActualizarAsistencia(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultarAsistencia(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultarResumenAsistencia(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AsistenciaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegistrarAsistenciaGrupal': grpc.unary_unary_rpc_method_handler(
                    servicer.RegistrarAsistenciaGrupal,
                    request_deserializer=asistencia__pb2.RegistrarAsistenciaGrupalRequest.FromString,
                    response_serializer=asistencia__pb2.AsistenciaListResponse.SerializeToString,
            ),
            'ActualizarAsistencia': grpc.unary_unary_rpc_method_handler(
                    servicer.ActualizarAsistencia,
                    request_deserializer=asistencia__pb2.ActualizarAsistenciaRequest.FromString,
                    response_serializer=asistencia__pb2.AsistenciaResponse.SerializeToString,
            ),
            'ConsultarAsistencia': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarAsistencia,
                    request_deserializer=asistencia__pb2.ConsultarAsistenciaRequest.FromString,
                    response_serializer=asistencia__pb2.AsistenciaListResponse.SerializeToString,
            ),
            'ConsultarResumenAsistencia': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarResumenAsistencia,
                    request_deserializer=asistencia__pb2.ConsultarResumenRequest.FromString,
                    response_serializer=asistencia__pb2.ResumenAsistenciaListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'asistencia.AsistenciaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('asistencia.AsistenciaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AsistenciaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegistrarAsistenciaGrupal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/asistencia.AsistenciaService/RegistrarAsistenciaGrupal',
            asistencia__pb2.RegistrarAsistenciaGrupalRequest.SerializeToString,
            asistencia__pb2.AsistenciaListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActualizarAsistencia(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/asistencia.AsistenciaService/ActualizarAsistencia',
            asistencia__pb2.ActualizarAsistenciaRequest.SerializeToString,
            asistencia__pb2.AsistenciaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsultarAsistencia(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/asistencia.AsistenciaService/ConsultarAsistencia',
            asistencia__pb2.ConsultarAsistenciaRequest.SerializeToString,
            asistencia__pb2.AsistenciaListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsultarResumenAsistencia(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/asistencia.AsistenciaService/ConsultarResumenAsistencia',
            asistencia__pb2.ConsultarResumenRequest.SerializeToString,
            asistencia__pb2.ResumenAsistenciaListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
