# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import contexto_docente_pb2 as contexto__docente__pb2

GRPC_GENERATED_VERSION = '1.65.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in contexto_docente_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class TeacherContextServiceStub(object):
    """Servicio expuesto por SGA Principal (9092) para que el Microservicio Docente (9091)
    consulte datos institucionales y valide permisos de manera segura.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ValidateTeacherAssignment = channel.unary_unary(
                '/sga.contexto.TeacherContextService/ValidateTeacherAssignment',
                request_serializer=contexto__docente__pb2.ValidateAssignmentRequest.SerializeToString,
                response_deserializer=contexto__docente__pb2.ValidateAssignmentResponse.FromString,
                _registered_method=True)
        self.GetStudentsByAssignment = channel.unary_unary(
                '/sga.contexto.TeacherContextService/GetStudentsByAssignment',
                request_serializer=contexto__docente__pb2.StudentsByAssignmentRequest.SerializeToString,
                response_deserializer=contexto__docente__pb2.StudentsByAssignmentResponse.FromString,
                _registered_method=True)
        self.ValidateStudentEnrollment = channel.unary_unary(
                '/sga.contexto.TeacherContextService/ValidateStudentEnrollment',
                request_serializer=contexto__docente__pb2.ValidateEnrollmentRequest.SerializeToString,
                response_deserializer=contexto__docente__pb2.ValidateEnrollmentResponse.FromString,
                _registered_method=True)
        self.GetCurrentAcademicYear = channel.unary_unary(
                '/sga.contexto.TeacherContextService/GetCurrentAcademicYear',
                request_serializer=contexto__docente__pb2.EmptyRequest.SerializeToString,
                response_deserializer=contexto__docente__pb2.AcademicYearResponse.FromString,
                _registered_method=True)


class TeacherContextServiceServicer(object):
    """Servicio expuesto por SGA Principal (9092) para que el Microservicio Docente (9091)
    consulte datos institucionales y valide permisos de manera segura.
    """

    def ValidateTeacherAssignment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStudentsByAssignment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateStudentEnrollment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCurrentAcademicYear(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TeacherContextServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ValidateTeacherAssignment': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateTeacherAssignment,
                    request_deserializer=contexto__docente__pb2.ValidateAssignmentRequest.FromString,
                    response_serializer=contexto__docente__pb2.ValidateAssignmentResponse.SerializeToString,
            ),
            'GetStudentsByAssignment': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStudentsByAssignment,
                    request_deserializer=contexto__docente__pb2.StudentsByAssignmentRequest.FromString,
                    response_serializer=contexto__docente__pb2.StudentsByAssignmentResponse.SerializeToString,
            ),
            'ValidateStudentEnrollment': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateStudentEnrollment,
                    request_deserializer=contexto__docente__pb2.ValidateEnrollmentRequest.FromString,
                    response_serializer=contexto__docente__pb2.ValidateEnrollmentResponse.SerializeToString,
            ),
            'GetCurrentAcademicYear': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentAcademicYear,
                    request_deserializer=contexto__docente__pb2.EmptyRequest.FromString,
                    response_serializer=contexto__docente__pb2.AcademicYearResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sga.contexto.TeacherContextService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sga.contexto.TeacherContextService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TeacherContextService(object):
    """Servicio expuesto por SGA Principal (9092) para que el Microservicio Docente (9091)
    consulte datos institucionales y valide permisos de manera segura.
    """

    @staticmethod
    def ValidateTeacherAssignment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sga.contexto.TeacherContextService/ValidateTeacherAssignment',
            contexto__docente__pb2.ValidateAssignmentRequest.SerializeToString,
            contexto__docente__pb2.ValidateAssignmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStudentsByAssignment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sga.contexto.TeacherContextService/GetStudentsByAssignment',
            contexto__docente__pb2.StudentsByAssignmentRequest.SerializeToString,
            contexto__docente__pb2.StudentsByAssignmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateStudentEnrollment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sga.contexto.TeacherContextService/ValidateStudentEnrollment',
            contexto__docente__pb2.ValidateEnrollmentRequest.SerializeToString,
            contexto__docente__pb2.ValidateEnrollmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCurrentAcademicYear(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sga.contexto.TeacherContextService/GetCurrentAcademicYear',
            contexto__docente__pb2.EmptyRequest.SerializeToString,
            contexto__docente__pb2.AcademicYearResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
