# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import docente_pb2 as docente__pb2

GRPC_GENERATED_VERSION = '1.65.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in docente_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class DocenteServiceStub(object):
    """Contrato compartido entre sga-principal (cliente) y MICRO-DOCENTE (servidor).
    MICRO-DOCENTE debe implementar este mismo .proto en Python (grpcio) para
    que ambos lados se entiendan.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ObtenerCalificaciones = channel.unary_unary(
                '/sga.docente.DocenteService/ObtenerCalificaciones',
                request_serializer=docente__pb2.ObtenerCalificacionesRequest.SerializeToString,
                response_deserializer=docente__pb2.ObtenerCalificacionesResponse.FromString,
                _registered_method=True)
        self.CalcularPromedioFormativo = channel.unary_unary(
                '/sga.docente.DocenteService/CalcularPromedioFormativo',
                request_serializer=docente__pb2.PromedioRequest.SerializeToString,
                response_deserializer=docente__pb2.PromedioResponse.FromString,
                _registered_method=True)
        self.CalcularPromedioFinal = channel.unary_unary(
                '/sga.docente.DocenteService/CalcularPromedioFinal',
                request_serializer=docente__pb2.PromedioRequest.SerializeToString,
                response_deserializer=docente__pb2.PromedioResponse.FromString,
                _registered_method=True)
        self.RegistrarCalificacion = channel.unary_unary(
                '/sga.docente.DocenteService/RegistrarCalificacion',
                request_serializer=docente__pb2.RegistrarCalificacionRequest.SerializeToString,
                response_deserializer=docente__pb2.RegistrarCalificacionResponse.FromString,
                _registered_method=True)
        self.ConvertirACualitativa = channel.unary_unary(
                '/sga.docente.DocenteService/ConvertirACualitativa',
                request_serializer=docente__pb2.ConvertirACualitativaRequest.SerializeToString,
                response_deserializer=docente__pb2.ConvertirACualitativaResponse.FromString,
                _registered_method=True)


class DocenteServiceServicer(object):
    """Contrato compartido entre sga-principal (cliente) y MICRO-DOCENTE (servidor).
    MICRO-DOCENTE debe implementar este mismo .proto en Python (grpcio) para
    que ambos lados se entiendan.
    """

    def ObtenerCalificaciones(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalcularPromedioFormativo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalcularPromedioFinal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegistrarCalificacion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConvertirACualitativa(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocenteServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ObtenerCalificaciones': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerCalificaciones,
                    request_deserializer=docente__pb2.ObtenerCalificacionesRequest.FromString,
                    response_serializer=docente__pb2.ObtenerCalificacionesResponse.SerializeToString,
            ),
            'CalcularPromedioFormativo': grpc.unary_unary_rpc_method_handler(
                    servicer.CalcularPromedioFormativo,
                    request_deserializer=docente__pb2.PromedioRequest.FromString,
                    response_serializer=docente__pb2.PromedioResponse.SerializeToString,
            ),
            'CalcularPromedioFinal': grpc.unary_unary_rpc_method_handler(
                    servicer.CalcularPromedioFinal,
                    request_deserializer=docente__pb2.PromedioRequest.FromString,
                    response_serializer=docente__pb2.PromedioResponse.SerializeToString,
            ),
            'RegistrarCalificacion': grpc.unary_unary_rpc_method_handler(
                    servicer.RegistrarCalificacion,
                    request_deserializer=docente__pb2.RegistrarCalificacionRequest.FromString,
                    response_serializer=docente__pb2.RegistrarCalificacionResponse.SerializeToString,
            ),
            'ConvertirACualitativa': grpc.unary_unary_rpc_method_handler(
                    servicer.ConvertirACualitativa,
                    request_deserializer=docente__pb2.ConvertirACualitativaRequest.FromString,
                    response_serializer=docente__pb2.ConvertirACualitativaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sga.docente.DocenteService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sga.docente.DocenteService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DocenteService(object):
    """Contrato compartido entre sga-principal (cliente) y MICRO-DOCENTE (servidor).
    MICRO-DOCENTE debe implementar este mismo .proto en Python (grpcio) para
    que ambos lados se entiendan.
    """

    @staticmethod
    def ObtenerCalificaciones(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sga.docente.DocenteService/ObtenerCalificaciones',
            docente__pb2.ObtenerCalificacionesRequest.SerializeToString,
            docente__pb2.ObtenerCalificacionesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalcularPromedioFormativo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sga.docente.DocenteService/CalcularPromedioFormativo',
            docente__pb2.PromedioRequest.SerializeToString,
            docente__pb2.PromedioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalcularPromedioFinal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sga.docente.DocenteService/CalcularPromedioFinal',
            docente__pb2.PromedioRequest.SerializeToString,
            docente__pb2.PromedioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegistrarCalificacion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sga.docente.DocenteService/RegistrarCalificacion',
            docente__pb2.RegistrarCalificacionRequest.SerializeToString,
            docente__pb2.RegistrarCalificacionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConvertirACualitativa(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sga.docente.DocenteService/ConvertirACualitativa',
            docente__pb2.ConvertirACualitativaRequest.SerializeToString,
            docente__pb2.ConvertirACualitativaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
