# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import principal_pb2 as principal__pb2

GRPC_GENERATED_VERSION = '1.65.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in principal_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class PrincipalServiceStub(object):
    """Contrato expuesto por sga-principal para que otros microservicios
    (Secretaría, Soporte, etc.) lean datos del núcleo sin tocar la BD directo.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListarEstudiantes = channel.unary_unary(
                '/sga.principal.PrincipalService/ListarEstudiantes',
                request_serializer=principal__pb2.ListarEstudiantesRequest.SerializeToString,
                response_deserializer=principal__pb2.ListarEstudiantesResponse.FromString,
                _registered_method=True)
        self.ObtenerEstudiante = channel.unary_unary(
                '/sga.principal.PrincipalService/ObtenerEstudiante',
                request_serializer=principal__pb2.ObtenerEstudianteRequest.SerializeToString,
                response_deserializer=principal__pb2.EstudianteProto.FromString,
                _registered_method=True)


class PrincipalServiceServicer(object):
    """Contrato expuesto por sga-principal para que otros microservicios
    (Secretaría, Soporte, etc.) lean datos del núcleo sin tocar la BD directo.
    """

    def ListarEstudiantes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerEstudiante(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PrincipalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListarEstudiantes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarEstudiantes,
                    request_deserializer=principal__pb2.ListarEstudiantesRequest.FromString,
                    response_serializer=principal__pb2.ListarEstudiantesResponse.SerializeToString,
            ),
            'ObtenerEstudiante': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerEstudiante,
                    request_deserializer=principal__pb2.ObtenerEstudianteRequest.FromString,
                    response_serializer=principal__pb2.EstudianteProto.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sga.principal.PrincipalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sga.principal.PrincipalService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PrincipalService(object):
    """Contrato expuesto por sga-principal para que otros microservicios
    (Secretaría, Soporte, etc.) lean datos del núcleo sin tocar la BD directo.
    """

    @staticmethod
    def ListarEstudiantes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sga.principal.PrincipalService/ListarEstudiantes',
            principal__pb2.ListarEstudiantesRequest.SerializeToString,
            principal__pb2.ListarEstudiantesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtenerEstudiante(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sga.principal.PrincipalService/ObtenerEstudiante',
            principal__pb2.ObtenerEstudianteRequest.SerializeToString,
            principal__pb2.EstudianteProto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
