# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: principal.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fprincipal.proto\x12\rsga.principal\"\xc7\x02\n\x0f\x45studianteProto\x12\x15\n\rid_estudiante\x18\x01 \x01(\x03\x12\x0e\n\x06\x63\x65\x64ula\x18\x02 \x01(\t\x12\x19\n\x11\x63odigo_estudiante\x18\x03 \x01(\t\x12\x0f\n\x07nombres\x18\x04 \x01(\t\x12\x11\n\tapellidos\x18\x05 \x01(\t\x12\x18\n\x10\x66\x65\x63ha_nacimiento\x18\x06 \x01(\t\x12\x0e\n\x06genero\x18\x07 \x01(\t\x12\x11\n\tdireccion\x18\x08 \x01(\t\x12\x10\n\x08telefono\x18\t \x01(\t\x12\x0e\n\x06\x63orreo\x18\n \x01(\t\x12\x14\n\x0c\x64iscapacidad\x18\x0b \x01(\x08\x12\x19\n\x11tipo_discapacidad\x18\x0c \x01(\t\x12\x17\n\x0fporcentaje_disc\x18\r \x01(\x05\x12\x0e\n\x06\x65stado\x18\x0e \x01(\t\x12\x15\n\rrepresentante\x18\x0f \x01(\t\"\x1a\n\x18ListarEstudiantesRequest\"P\n\x19ListarEstudiantesResponse\x12\x33\n\x0b\x65studiantes\x18\x01 \x03(\x0b\x32\x1e.sga.principal.EstudianteProto\"1\n\x18ObtenerEstudianteRequest\x12\x15\n\rid_estudiante\x18\x01 \x01(\x03\x32\xd8\x01\n\x10PrincipalService\x12\x66\n\x11ListarEstudiantes\x12\'.sga.principal.ListarEstudiantesRequest\x1a(.sga.principal.ListarEstudiantesResponse\x12\\\n\x11ObtenerEstudiante\x12\'.sga.principal.ObtenerEstudianteRequest\x1a\x1e.sga.principal.EstudianteProtoB\"\n\x1e\x65\x63.edu.uteq.sga.grpc.principalP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'principal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036ec.edu.uteq.sga.grpc.principalP\001'
  _globals['_ESTUDIANTEPROTO']._serialized_start=35
  _globals['_ESTUDIANTEPROTO']._serialized_end=362
  _globals['_LISTARESTUDIANTESREQUEST']._serialized_start=364
  _globals['_LISTARESTUDIANTESREQUEST']._serialized_end=390
  _globals['_LISTARESTUDIANTESRESPONSE']._serialized_start=392
  _globals['_LISTARESTUDIANTESRESPONSE']._serialized_end=472
  _globals['_OBTENERESTUDIANTEREQUEST']._serialized_start=474
  _globals['_OBTENERESTUDIANTEREQUEST']._serialized_end=523
  _globals['_PRINCIPALSERVICE']._serialized_start=526
  _globals['_PRINCIPALSERVICE']._serialized_end=742
# @@protoc_insertion_point(module_scope)
