# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import representante_academico_pb2 as representante__academico__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in representante_academico_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RepresentanteAcademicoServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConsultarCalificaciones = channel.unary_unary(
                '/representante_academico.RepresentanteAcademicoService/ConsultarCalificaciones',
                request_serializer=representante__academico__pb2.MatriculasRequest.SerializeToString,
                response_deserializer=representante__academico__pb2.CalificacionesResponse.FromString,
                _registered_method=True)
        self.ConsultarAsistencia = channel.unary_unary(
                '/representante_academico.RepresentanteAcademicoService/ConsultarAsistencia',
                request_serializer=representante__academico__pb2.MatriculasRequest.SerializeToString,
                response_deserializer=representante__academico__pb2.AsistenciaResponse.FromString,
                _registered_method=True)
        self.ConsultarComunicados = channel.unary_unary(
                '/representante_academico.RepresentanteAcademicoService/ConsultarComunicados',
                request_serializer=representante__academico__pb2.AsignacionesRequest.SerializeToString,
                response_deserializer=representante__academico__pb2.ComunicadosResponse.FromString,
                _registered_method=True)


class RepresentanteAcademicoServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ConsultarCalificaciones(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultarAsistencia(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultarComunicados(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RepresentanteAcademicoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConsultarCalificaciones': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarCalificaciones,
                    request_deserializer=representante__academico__pb2.MatriculasRequest.FromString,
                    response_serializer=representante__academico__pb2.CalificacionesResponse.SerializeToString,
            ),
            'ConsultarAsistencia': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarAsistencia,
                    request_deserializer=representante__academico__pb2.MatriculasRequest.FromString,
                    response_serializer=representante__academico__pb2.AsistenciaResponse.SerializeToString,
            ),
            'ConsultarComunicados': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarComunicados,
                    request_deserializer=representante__academico__pb2.AsignacionesRequest.FromString,
                    response_serializer=representante__academico__pb2.ComunicadosResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'representante_academico.RepresentanteAcademicoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('representante_academico.RepresentanteAcademicoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RepresentanteAcademicoService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ConsultarCalificaciones(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/representante_academico.RepresentanteAcademicoService/ConsultarCalificaciones',
            representante__academico__pb2.MatriculasRequest.SerializeToString,
            representante__academico__pb2.CalificacionesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsultarAsistencia(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/representante_academico.RepresentanteAcademicoService/ConsultarAsistencia',
            representante__academico__pb2.MatriculasRequest.SerializeToString,
            representante__academico__pb2.AsistenciaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsultarComunicados(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/representante_academico.RepresentanteAcademicoService/ConsultarComunicados',
            representante__academico__pb2.AsignacionesRequest.SerializeToString,
            representante__academico__pb2.ComunicadosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
